"""Task stream generation.

Owner: member 1.

Follows Ma et al. (2017): a fixed sequence of delivery tasks is generated by
choosing pickup and delivery locations at random from the task endpoints,
and the tasks are then added to the task set in order, ``arrival_rate`` tasks
per timestep. The paper uses 500 tasks and rates 0.2, 0.5, 1, 2, 5 and 10.
"""

from __future__ import annotations

import math
import random
from fractions import Fraction

from foresight.interfaces import Task
from foresight.sim.grid import GridMap


def release_times(n_tasks: int, arrival_rate: float) -> list[int]:
    """Release time of each task when ``arrival_rate`` tasks arrive per step.

    Task k is released at ``floor(k / arrival_rate)``, so a rate of 0.2 gives
    0, 5, 10, ... and a rate of 2 gives 0, 0, 1, 1, ... The rate is converted
    to an exact fraction to avoid float rounding (e.g. 3 / 0.2 = 14.999...).
    """
    if arrival_rate <= 0:
        raise ValueError("arrival_rate must be positive")
    rate = Fraction(str(arrival_rate))
    return [math.floor(k / rate) for k in range(n_tasks)]


def generate_task_stream(
    grid: GridMap, n_tasks: int, arrival_rate: float, seed: int
) -> list[Task]:
    """Generate a finite stream of ``n_tasks`` tasks.

    Pickup and delivery are distinct cells drawn uniformly from
    ``grid.task_endpoints``. Locations depend only on ``seed``, not on
    ``arrival_rate``, so the same seed gives the same task sequence at every
    rate. Every method is evaluated on identical streams (common random
    numbers).
    """
    endpoints = grid.task_endpoints
    if len(endpoints) < 2:
        raise ValueError("need at least two task endpoints")
    rng = random.Random(seed)
    tasks = []
    for k, t in enumerate(release_times(n_tasks, arrival_rate)):
        pickup, delivery = rng.sample(endpoints, 2)
        tasks.append(Task(task_id=k, pickup=pickup, delivery=delivery, release_time=t))
    return tasks
